import Breadcrumbs from "@/components/Breadcrumbs";
import { pageMetadata } from "@/lib/metadata";
import { site } from "@/lib/site";

export const metadata = pageMetadata({ title: "Website Privacy Information", description: "How this website handles booking links, interactive maps and third-party services. Contact Psychologist Chandni Akhenia with website privacy questions.", path: "/privacy/" });
export default function PrivacyPage() {
  return <main id="main" className="inner-page"><section className="page-intro"><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Website privacy", href: "/privacy/" }]} /><div className="page-title-block"><p className="eyebrow">Website information · 7 October 2026</p><h1>Your privacy <em>on this website.</em></h1><p className="lead">Clear information about the website and the services you choose to open from it.</p></div></div></section><div className="shell privacy-copy">
    <section className="article-section"><h2>Browsing and booking</h2><p>This website has no patient account or contact form. Its code does not add an advertising tracker or an analytics service. The hosting provider, GitHub Pages, may process technical request information, such as your IP address and browser information, to deliver and secure the website.</p><p>Booking buttons open WhatsApp, your phone application or your email application. Information you send is handled through that chosen service and its privacy terms. For an initial appointment request, sharing contact and scheduling information is enough; avoid sending detailed health histories through an ordinary booking message.</p></section>
    <section className="article-section"><h2>Maps and external links</h2><p>The interactive Google Map loads only when you select “Load interactive map”. Loading it connects your browser to Google, which may process technical information and use cookies under its own policies. Opening directions, social profiles or article sources also takes you to external services.</p><p>Fonts are served with the website’s own assets. External websites and communication services have separate privacy policies: <a className="text-link" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">GitHub</a>, <a className="text-link" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google</a> and <a className="text-link" href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">WhatsApp</a>.</p></section>
    <section className="article-section"><h2>Consultation confidentiality</h2><p>Website privacy and consultation confidentiality are different matters. Confidentiality, consent, records and any legal or safety-related limits are discussed as part of care. This page does not replace those arrangements.</p><p>For questions about the website or how to contact the practice privately, email <a className="text-link" href={"mailto:" + site.email}>{site.email}</a>.</p></section>
  </div></main>;
}
