export type ArticleSource = { title: string; url: string };
export type ArticleSection = { id: string; title: string; paragraphs: string[]; bullets?: string[]; source?: ArticleSource };
export type Article = {
  slug: string; title: string; category: string; summary: string; description: string;
  intro: string; sections: ArticleSection[]; relatedServices: string[];
};

export const articlePublishedDate = "2026-10-07";
const psychotherapy = { title: "NIMH: Psychotherapies", url: "https://www.nimh.nih.gov/health/topics/psychotherapies" };
const anxiety = { title: "WHO: Anxiety disorders", url: "https://www.who.int/news-room/fact-sheets/detail/anxiety-disorders" };
const burnout = { title: "WHO: Burn-out as an occupational phenomenon", url: "https://www.who.int/standards/classifications/frequently-asked-questions/burn-out-an-occupational-phenomenon" };
const sleep = { title: "NHS: Insomnia", url: "https://www.nhs.uk/conditions/insomnia/" };
const relationships = { title: "NHS: Maintaining healthy relationships", url: "https://www.nhs.uk/every-mind-matters/lifes-challenges/maintaining-healthy-relationships-and-mental-wellbeing/" };
const grief = { title: "NHS: Grief, bereavement and loss", url: "https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/grief-bereavement-loss/" };
const adolescents = { title: "WHO: Mental health of adolescents", url: "https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health" };
const online = { title: "NIMH: Getting mental health support virtually", url: "https://www.nimh.nih.gov/health/publications/what-is-telemental-health" };
const perfectionism = { title: "Centre for Clinical Interventions: Perfectionism", url: "https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Perfectionism" };
const loneliness = { title: "NHS: Feeling lonely", url: "https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/feeling-lonely/" };

export const articles: Article[] = [
  {
    slug: "first-psychology-session", title: "Your first psychology session: what to expect", category: "Starting therapy",
    summary: "A practical guide to preparing, asking questions and deciding on the next step.",
    description: "Prepare for a first psychology consultation in Malad West, Mumbai. Learn what to discuss, which questions to ask and how to book with Chandni Akhenia.",
    intro: "Booking a first appointment can bring relief and uncertainty together. You do not need a diagnosis, a polished explanation or a clear plan before beginning. The first conversation is a place to work out what you need.",
    sections: [
      { id: "before", title: "Before you arrive", paragraphs: ["Think about one recent situation you would like to understand. It might be a difficult conversation, a change in sleep or a worry that keeps returning. A short note can help if speaking feels difficult, but notes are optional.", "When booking, ask about the fee, session length, language options and cancellation arrangements. Mention whether you prefer the Malad West appointment location or an online consultation. These practical questions are a reasonable part of choosing care."] },
      { id: "conversation", title: "What the conversation may cover", paragraphs: ["You can describe what brought you in, how long it has been happening and what feels harder in daily life. Relevant health history, previous support and your own priorities may help the psychologist understand the context. You can say when you would prefer to leave something for later.", "The first session also gives you an opportunity to ask about the approach, professional experience, confidentiality and how progress will be discussed. NIMH recommends clarifying these questions when choosing a therapist."], source: psychotherapy },
      { id: "questions", title: "Questions you can bring", paragraphs: ["You are allowed to ask for an explanation in everyday language. The aim is to understand the process well enough to make an informed choice, rather than agree to a long course of sessions before your needs are clear."], bullets: ["What might our initial goals be?", "How will we decide the frequency of sessions?", "What are the limits of confidentiality?", "What happens if this approach does not feel like a good fit?"] },
      { id: "after", title: "After the first meeting", paragraphs: ["You may leave with an initial plan, more questions or a recommendation for another kind of assessment. A first visit does not need to resolve everything. Consider whether you felt heard, could ask questions and understood the proposed next step.", "If something was unclear, bring it up before the next appointment. Appointments with Chandni are arranged by prior booking. You can request a first conversation in Malad West or ask whether online support would suit your situation."] }
    ], relatedServices: ["online-psychology-consultation", "anxiety", "self-esteem-personal-growth"]
  },
  {
    slug: "anxiety-and-everyday-stress", title: "Anxiety and everyday stress: noticing the pattern", category: "Anxiety & stress",
    summary: "Look at the effect on daily life without trying to diagnose yourself from a checklist.",
    description: "Understand anxiety, worry and everyday stress, and when to seek support. Counselling appointments with Chandni Akhenia in Malad West, Mumbai and online.",
    intro: "A busy week, a difficult decision or uncertainty about the future can bring worry. The useful question is often how the experience affects your life, rather than which label fits it immediately.",
    sections: [
      { id: "notice", title: "Notice what changes", paragraphs: ["Anxiety can involve worry, tension, difficulty concentrating, disturbed sleep or avoiding situations. WHO describes anxiety disorders as patterns of intense fear or worry that cause distress and interfere with daily life. A few familiar symptoms do not establish a diagnosis.", "Instead of repeatedly checking an online symptom list, describe what happens in your own words. For example: ‘I keep rehearsing conversations and have stopped joining meetings.’ That gives a consultation a clearer starting point."], source: anxiety },
      { id: "context", title: "Make room for context", paragraphs: ["A deadline, family pressure, poor rest or an unfamiliar setting may be part of the picture. Ask yourself what was happening before the worry increased and what you do when it arrives. Does avoiding a task bring short relief but make tomorrow harder?", "A simple note of the situation, your response and its effect can help you explain the pattern. This is information to discuss, not a score to monitor or a test you need to pass."] },
      { id: "steps", title: "Choose one manageable next step", paragraphs: ["You could start by making space for a regular meal, a brief break or a conversation with someone you trust. Choose something realistic for the day you are having. If a breathing or relaxation exercise feels uncomfortable, stop and discuss another option rather than forcing it.", "If worry is making a particular responsibility difficult, break the next action into a small practical step. The purpose is to learn what helps you begin, not to prove that you should be able to handle everything alone."] },
      { id: "support", title: "When a consultation may help", paragraphs: ["Consider support when worry keeps returning, changes your routine or makes work, study and relationships difficult. You can bring examples rather than a diagnosis. A psychologist can explore the pattern and discuss an appropriate next step with you.", "Physical symptoms can have causes beyond anxiety. New or severe chest pain, breathing difficulty or other urgent symptoms need medical attention. Counselling does not replace a physical health assessment. Chandni offers appointments in Malad West and online by prior booking."] }
    ], relatedServices: ["anxiety", "stress-workplace-burnout", "sleep-problems"]
  },
  {
    slug: "workplace-burnout-and-boundaries", title: "Workplace burnout: looking beyond a difficult week", category: "Work & wellbeing",
    summary: "Explore workload, recovery and practical boundaries without blaming yourself for exhaustion.",
    description: "Explore workplace burnout, recovery and realistic boundaries. Psychological counselling with Chandni Akhenia in Malad West, Mumbai and online.",
    intro: "When work takes up every available part of the day, exhaustion can start to feel normal. A useful conversation considers the demands around you as well as the ways you are trying to cope.",
    sections: [
      { id: "meaning", title: "What burnout means", paragraphs: ["WHO uses burnout specifically for the occupational context. Its description includes exhaustion, growing distance or negativity towards work, and reduced professional effectiveness. It is an occupational phenomenon, not a medical diagnosis.", "Feeling depleted does not tell you by itself whether burnout, low mood, a sleep problem or a physical health concern is involved. Avoid treating a checklist as a conclusion; explain the changes and their impact during an assessment."], source: burnout },
      { id: "demands", title: "Look at the demands, not just your habits", paragraphs: ["Write down the expectations that are difficult to meet: overlapping deadlines, messages outside work hours, unclear responsibilities or insufficient support. Separate requirements you can negotiate from conditions that need a wider workplace response.", "A walk or a quiet evening may be welcome, but it cannot by itself change an unsustainable workload. In a counselling conversation you can examine what support is available and what choices feel feasible, without being told that a single routine will solve the situation."] },
      { id: "boundaries", title: "Make a boundary specific", paragraphs: ["A boundary is easier to discuss when it describes an action. For example: ‘If a new urgent task comes in, which existing deadline should move?’ or ‘I can respond to routine messages when my workday starts.’ Adapt the wording to your role and safety at work.", "You do not have to confront every issue at once. Choose one conversation you can prepare for, consider whom to involve and decide what you will do if the request is not accepted. Not every workplace gives people equal freedom to negotiate."] },
      { id: "help", title: "Bring the pattern into a consultation", paragraphs: ["You can talk about sleep, concentration, irritability, motivation and the effect on relationships outside work. Bring a typical week rather than a productivity target. A consultation can help clarify priorities and whether psychological or medical support is needed.", "If you feel persistently low, cannot manage ordinary tasks or are concerned about your safety, seek professional support promptly. Chandni’s stress and workplace burnout appointments are available in Malad West and online by prior booking."] }
    ], relatedServices: ["stress-workplace-burnout", "productivity-focus", "depression"]
  },
  {
    slug: "sleep-and-night-time-worry", title: "When worry follows you to bed", category: "Rest & routines",
    summary: "A starting point for discussing sleep difficulties, with attention to possible medical causes.",
    description: "Learn how to describe sleep difficulties and night-time worry, and when to seek medical review or counselling in Malad West, Mumbai.",
    intro: "At the end of a demanding day, a quiet room can leave more space for unfinished thoughts. Sleep difficulties deserve attention, but they are not a reason to blame yourself or chase a perfect bedtime routine.",
    sections: [
      { id: "pattern", title: "Describe the pattern", paragraphs: ["Are you finding it difficult to fall asleep, waking repeatedly or waking early? How is the next day affected? A few optional notes about bedtime, waking and daytime tiredness can be more useful in a consultation than a single number from an app.", "The NHS notes that sleep difficulties can have several causes, including stress, substances, medicines and health conditions. It is sensible to consider these possibilities rather than assume that worry explains every change."], source: sleep },
      { id: "evening", title: "Keep the evening manageable", paragraphs: ["You might set aside a short period earlier in the evening to write down the next practical action for tomorrow. If a thought has no action you can take tonight, make a note to discuss it later rather than repeatedly trying to finish the problem in bed.", "Choose a wind-down activity that feels ordinary and comfortable. The aim is a workable transition away from tasks. It does not need to include expensive products, a strict ritual or another list of rules to get right."] },
      { id: "pressure", title: "Avoid making sleep another performance task", paragraphs: ["If you find yourself repeatedly calculating how many hours remain, mention that pattern when seeking support. Describe the pressure you feel about sleep and what happens the next day. A clinician can help consider an approach that fits the whole situation.", "Do not change a prescribed medicine or start sleep medication based on an article. Ask the prescribing clinician or a suitable medical professional about medication questions. A psychologist does not prescribe medication."] },
      { id: "assessment", title: "When to ask for an assessment", paragraphs: ["Speak to a health professional if the difficulty persists, affects everyday functioning or concerns you. Loud snoring, reported breathing pauses or severe daytime sleepiness are reasons to discuss medical assessment, rather than rely on counselling alone.", "If tiredness makes driving unsafe, stop and arrange a safer way to travel. For psychological concerns around worry, routines or stress, you can request a counselling appointment with Chandni in Malad West or ask about online support."] }
    ], relatedServices: ["sleep-problems", "anxiety", "stress-workplace-burnout"]
  },
  {
    slug: "relationship-communication", title: "Having a difficult relationship conversation", category: "Relationships",
    summary: "Prepare for a clearer conversation about needs, boundaries and recurring disagreements.",
    description: "Explore respectful relationship communication and when couples counselling may help. Appointments in Malad West, Mumbai and online.",
    intro: "A disagreement may begin with one small event and quickly become a conversation about everything that has felt unresolved. You do not need to solve every issue in a single discussion.",
    sections: [
      { id: "prepare", title: "Choose one concern and a suitable time", paragraphs: ["Decide what you want the other person to understand. A concrete example is usually clearer than ‘you always’ or ‘you never’. You could begin with what happened, how it affected you and one request you would like to discuss.", "Ask whether this is a workable time to talk. The NHS recommends open conversations, checking your understanding and returning to a disagreement when everyone is calmer. These are starting points, not rules that guarantee agreement."], source: relationships },
      { id: "listen", title: "Check that you have understood", paragraphs: ["Before explaining your position again, try putting the other person’s concern into your own words and asking whether you have understood it. Listening does not require accepting every claim or abandoning your own needs.", "If the discussion moves through several unrelated issues, write them down and choose one to return to. You might discover that you disagree about an event, have different expectations or need more time to consider an important decision."] },
      { id: "pause", title: "Agree on what a pause means", paragraphs: ["A pause is more useful when it includes a plan to return to the conversation. For example: ‘I need a break. Can we return to this after dinner?’ This gives both people a chance to understand what is being requested.", "If a conversation includes threats, intimidation, coercion or violence, prioritise safety. Communication exercises and joint counselling are not a substitute for appropriate individual or specialist support. You do not need to negotiate your safety in a shared session."] },
      { id: "counselling", title: "When counselling may be useful", paragraphs: ["You can ask for support if disagreements keep returning, important needs are difficult to express or you are unsure what you want to do next. Counselling can provide a structured place to explore the pattern; it does not guarantee reconciliation or prescribe a relationship decision.", "One partner can request an individual consultation. For joint sessions, consent, goals and confidentiality arrangements need to be clear to both people. Chandni offers relationship counselling in Malad West and can discuss whether an online format is suitable."] }
    ], relatedServices: ["relationship-couples-counselling", "self-esteem-personal-growth", "stress-workplace-burnout"]
  },
  {
    slug: "grief-without-a-timeline", title: "Grief does not need a timetable", category: "Loss & change",
    summary: "Making room for mixed feelings, everyday needs and the support you want after a loss.",
    description: "Read about grief, everyday support and seeking counselling after a loss. Appointments with Chandni Akhenia in Malad West, Mumbai and online.",
    intro: "A loss can change familiar routines as well as the way you feel. Some moments may feel ordinary, while others feel unexpectedly difficult. You do not have to explain that mixture neatly to deserve support.",
    sections: [
      { id: "feelings", title: "There is no required sequence of feelings", paragraphs: ["The NHS explains that grief may involve sadness, shock, anger, guilt or exhaustion, and that people do not necessarily experience stages in a fixed order. The presence or absence of a particular feeling is not a test of how much the loss matters.", "You may want to talk, stay quiet, remember the person or focus on practical needs. Preferences can change. It can help to tell people what is useful today rather than assume you must accept every suggestion."], source: grief },
      { id: "practical", title: "Name the practical support you need", paragraphs: ["Someone may want to help but not know what to do. If possible, make a specific request: company for an appointment, help with a meal or time to talk without advice. You can also say when you would prefer some space.", "For difficult dates or events, consider who you might contact and what responsibilities could be simplified. A plan can include leaving an event early or marking the occasion privately. It does not need to look like someone else’s way of remembering."] },
      { id: "others", title: "Different people can grieve differently", paragraphs: ["When family members respond in different ways, it can be hard to feel understood. One person may want conversation while another focuses on tasks. You can describe what you need without deciding that one response is the correct one.", "An ordinary enjoyable moment does not erase a loss. If you find yourself judging your reactions, bring that concern into a supportive conversation. There is no requirement to maintain a particular emotion all day."] },
      { id: "support", title: "You can seek support whenever you want it", paragraphs: ["You do not need to wait for a set number of weeks before asking for counselling. A consultation can begin with what daily life is like now, even if you do not want to describe the loss in detail.", "If grief is accompanied by severe low mood, inability to manage basic needs or thoughts of harming yourself, seek prompt professional help. In immediate danger, contact emergency services. Chandni offers grief and loss consultations in Malad West and online by prior booking."] }
    ], relatedServices: ["grief-loss", "depression", "self-esteem-personal-growth"]
  },
  {
    slug: "supporting-a-teenager", title: "Starting a mental health conversation with a teenager", category: "Teens & families",
    summary: "How to listen, discuss support and clarify privacy without turning a conversation into an interrogation.",
    description: "A guide for caregivers starting a mental health conversation with a teenager, with adolescent support available in Malad West, Mumbai.",
    intro: "When you notice a change in a teenager, it can be tempting to ask every question at once. Starting with curiosity and one clear observation may make it easier to hear what they want you to know.",
    sections: [
      { id: "changes", title: "Notice changes without applying a label", paragraphs: ["WHO identifies adolescence as an important period for emotional wellbeing, with family, school and social environments all playing a part. A persistent change in mood, sleep, friendships or functioning deserves attention, but a difficult day does not establish a disorder.", "Describe what you have noticed: ‘You seem to be finding mornings harder lately.’ Leave room for the young person to correct your interpretation. Their explanation may include concerns you have not seen."], source: adolescents },
      { id: "listen", title: "Ask what kind of conversation would help", paragraphs: ["You might ask whether they want listening, help thinking through a problem or practical support. If they do not want to talk immediately, agree on another opportunity and keep ordinary contact available.", "Avoid promising that you will keep absolutely everything secret. Explain calmly that if someone is at risk of harm you may need help from another adult or a professional. Privacy and safety should be discussed clearly, rather than introduced only after a crisis."] },
      { id: "appointment", title: "Explain an appointment before arranging it", paragraphs: ["A first consultation can explore what is happening and which next step fits. Ask the psychologist about age suitability, consent, caregiver involvement and the young person’s privacy. Do not assume that a caregiver will hear every detail or be excluded from every part of care.", "Invite the teenager to bring their own questions. You can explain the appointment location, travel and what the first conversation may involve. It is better to be clear about the purpose than present the appointment as a punishment for behaviour."] },
      { id: "safety", title: "Take safety concerns seriously", paragraphs: ["If a young person mentions self-harm, suicide, abuse or an immediate danger, seek appropriate professional or emergency support promptly. Do not wait for a routine booking if they cannot remain safe.", "For ongoing concerns about emotions, school pressure or relationships, you can discuss an adolescent consultation with Chandni in Malad West. Whether an online appointment fits depends on privacy, consent, caregiver arrangements and the young person’s needs."] }
    ], relatedServices: ["teen-adolescent-mental-health", "anxiety", "depression"]
  },
  {
    slug: "preparing-for-online-counselling", title: "Preparing for an online counselling appointment", category: "Starting therapy",
    summary: "A practical checklist for privacy, connection, suitability and a backup plan.",
    description: "Prepare for online counselling with Chandni Akhenia in Malad West, Mumbai. Consider privacy, your connection, suitability and what to ask before booking.",
    intro: "An online appointment can remove a journey from your day, but it still deserves protected time and a setting where you can speak comfortably. A little preparation can make the format easier to use.",
    sections: [
      { id: "fit", title: "Check whether the format fits", paragraphs: ["NIMH describes possible advantages of virtual care, including easier access without travel, alongside challenges such as connection problems and being overheard. Convenience does not make online support suitable for every concern or situation.", "Tell the psychologist where you will join from and ask about suitability, the platform, fees and session arrangements. An initial consultation can clarify whether online care, in-person care or another service is a better next step."], source: online },
      { id: "privacy", title: "Choose a private setting", paragraphs: ["Use a space where you can speak without being overheard. Headphones can help you hear, but they do not stop someone nearby from hearing your own voice. Consider shared devices, notifications and whether your screen is visible to others.", "If privacy at home is not possible, say so before the appointment. Do not join while driving or in another situation that needs your attention. You can ask about alternatives rather than trying to manage an unsuitable setting in silence."] },
      { id: "connection", title: "Make a simple connection plan", paragraphs: ["Check that your device is charged and the connection works. Keep the practice contact details available and agree on what to do if the call drops. A backup plan should be discussed before it is needed.", "For the first conversation, a few optional notes can help: what you want to discuss, when the concern began and questions about the process. You do not need to prepare a complete personal history or send sensitive documents through a booking message."] },
      { id: "expectations", title: "Clarify boundaries and urgent support", paragraphs: ["Ask how confidentiality is handled, whether sessions are recorded, how contact between appointments works and what to do outside session hours. Do not assume a booking chat is monitored continuously or is a place for emergency care.", "Online appointments with Chandni are arranged by prior booking. If there is immediate danger or an urgent need for in-person assessment, contact local emergency services or the appropriate local health service instead of waiting for an online session."] }
    ], relatedServices: ["online-psychology-consultation", "anxiety", "relationship-couples-counselling"]
  },
  {
    slug: "perfectionism-and-self-criticism", title: "When high standards turn into self-criticism", category: "Self-understanding",
    summary: "Explore the cost of rigid expectations and prepare a more balanced conversation about achievement.",
    description: "Explore perfectionism, self-criticism and rigid expectations. Counselling for self-esteem and personal growth in Malad West, Mumbai and online.",
    intro: "Caring about your work and wanting to improve are not problems in themselves. The question is whether your standards leave room for rest, learning and a sense of worth beyond the result.",
    sections: [
      { id: "cost", title: "Look at the cost of the standard", paragraphs: ["The Centre for Clinical Interventions describes unhelpful perfectionism in terms of demanding standards, self-worth tied strongly to achievement and continuing despite negative consequences. The goal is not to give up on what matters to you, but to examine standards that are difficult to live with.", "Notice a specific example: rewriting an ordinary email repeatedly, postponing a task because it might not be excellent or finding it hard to accept work that meets the actual requirement. The context and impact matter more than a label."], source: perfectionism },
      { id: "rules", title: "Put the rule into words", paragraphs: ["Try completing the sentence: ‘If I do not get this right, it means…’ You might notice a fear about being judged, disappointing someone or losing an opportunity. Treat that answer as a concern to understand, not another reason to criticise yourself.", "Ask what the task actually requires and who has set that requirement. Sometimes a practical standard is being replaced by a much stricter personal rule. Being able to name the difference can give a counselling conversation a clearer focus."] },
      { id: "experiment", title: "Choose a low-stakes example to discuss", paragraphs: ["You can bring one task where the cost of repeated checking feels larger than the benefit. Discuss what ‘finished’ could mean and what makes stopping difficult. Start with something that is safe to explore rather than a decision with serious consequences.", "The aim is curiosity about the pattern. If an exercise becomes another performance target, that is useful information to share. Support can take account of your responsibilities and the pressures around you, rather than assume everything is a matter of attitude."] },
      { id: "care", title: "When support may be useful", paragraphs: ["Consider counselling when self-criticism affects rest, relationships, work or the ability to begin meaningful tasks. You can ask for support without needing a diagnosis. A first conversation can focus on the pattern you want to understand.", "Chandni offers self-esteem and personal growth consultations in Malad West and online. Sessions can explore expectations, values and practical changes at a pace agreed with you. Neither an article nor a consultation promises a particular outcome."] }
    ], relatedServices: ["self-esteem-personal-growth", "productivity-focus", "anxiety"]
  },
  {
    slug: "loneliness-and-reconnection", title: "Loneliness: finding a manageable way to reconnect", category: "Connection & wellbeing",
    summary: "Start with the kind of connection you miss, rather than pressure to fill your social calendar.",
    description: "Explore loneliness, meaningful connection and asking for support. Psychology consultations with Chandni Akhenia in Malad West, Mumbai and online.",
    intro: "You can feel lonely while living alone, in a busy household or among people you know. What is missing may be company, understanding or a place where you feel able to be yourself.",
    sections: [
      { id: "meaning", title: "Name the connection you miss", paragraphs: ["The NHS notes that loneliness can arise in many situations, including a move, bereavement or a life change, and that someone can feel lonely in company. That distinction may help explain why simply adding more social events does not always address what feels missing.", "Ask yourself what you would want from a connection: an ordinary shared activity, someone to talk to, a sense of belonging or practical support. There is no single correct answer, and it may change over time."], source: loneliness },
      { id: "step", title: "Make the next step small enough", paragraphs: ["Choose one manageable invitation or activity. You might send a message suggesting a brief call, attend an activity that interests you or reconnect with someone you have been thinking about. You do not need to begin with a crowded event or a deeply personal conversation.", "Consider what would make that step easier: a familiar place, a shorter visit or permission to leave when you need to. If an invitation is declined, it gives you information about that moment; it is not a complete judgement about you."] },
      { id: "obstacles", title: "Notice the practical obstacles", paragraphs: ["Time, money, accessibility, caregiving and travel can all shape what is possible. A plan needs to fit those realities. You may be looking for a regular small contact rather than an activity that requires more energy than you have.", "If fear of judgement or past relationship experiences make contact difficult, bring that into a conversation with a psychologist. You do not have to solve every obstacle before seeking support, and you are not required to share more than you choose."] },
      { id: "support", title: "Ask for help if it feels hard to carry", paragraphs: ["A consultation can explore what loneliness means in your circumstances and what you want to change. It can also consider other concerns, such as low mood, grief or anxiety, without assuming that loneliness is itself a diagnosis.", "If you are struggling to cope, daily routines have become difficult or you are concerned about your safety, seek professional help promptly. Chandni offers consultations in Malad West and online by prior booking for relationship, emotional wellbeing and related concerns."] }
    ], relatedServices: ["relationship-couples-counselling", "depression", "grief-loss"]
  }
];

export const articleBySlug = new Map(articles.map((article) => [article.slug, article]));
export function articlePath(slug: string) { return "/articles/" + slug + "/"; }
export function readingMinutes(article: Article) {
  const text = [article.intro, ...article.sections.flatMap((section) => [...section.paragraphs, ...(section.bullets || [])])].join(" ");
  return Math.max(1, Math.ceil(text.split(/\s+/).length / 200));
}
